baseURL         = "http://212.71.254.23"
languageCode    = "en-us"
#title           = "My New Hugo Site"
theme           = "hello-friend-ng"

[Author]
name = "Carles Hernandez-Ferrer"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "bioinformatician, software developer, and data analyst"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Personal page"
  keywords = "homepage, blog"
  images = [""]

[languages]
  [languages.en]
    title = "Carles Hernandez-Ferrer"
    #subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "C:\\carles.exe"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "academic"
    name       = "Academic"
    url        = "/academic"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
  [[menu.main]]
    identifier = "fun"
    name       = "Fun"
    url        = "/fun"